Use CORS config to allow credentials
fuglede/vue-flask-azure-ad pull request #1
Opened 2021-01-27 09:29 UTC by Japanuspus

As we discussed, I tried using CORS config instead of the manual `Access-Control-Allow-Credentials`-header. I also moved all the ID's to a `.env.local`-file because it took my en embarrassing amount of time to get them all inserted to run this. Feel free to cherry-pick.
Note that I added a dotenv dependency to `requirements.txt`.

2021-01-27 09:52 UTC, fuglede requested changes

2021-01-27 09:52 UTC, fuglede commented on api/api.py
> +    supports_credentials = True,  # does not appear to be needed?
Heh, but I guess you left it in here for a reason?

I seem to recall needing that parameter when doing NTLM at some point, but other than that, never looked into it.

2021-01-27 09:52 UTC, fuglede commented on app/dotenv.local.template
> +VUE_APP_AZURE_OAUTH_BACKEND_APPLICATION_ID=####
Hey, this is a great way of combining the two. I had thought a bit about going all the way to cookiecutter, but that felt like it just added more noise. This is much better.

Could you update `README.md` accordingly?

2021-01-27 10:02 UTC, Japanuspus commented on api/api.py
> +    supports_credentials = True,  # does not appear to be needed?
Mostly because my "testing" was just pressing the button in the client, so I wasn't sure if this was needed elsewhere. Also, since the requirement for this might pop up later, I didn't want to rip it out completely.

How about commenting out the whole line?

2021-01-27 10:22 UTC, fuglede commented on api/api.py
> +    supports_credentials = True,  # does not appear to be needed?
If you think having it as a comment would be better UX, then yep, we can keep it around. I can't come up with a good example where we'd want authenticated requests when we already use OAuth(?), so I'd be tempted to just get rid of it altogether.

In either case, no strong opinions.

2021-02-02 10:15 UTC, fuglede commented on api/api.py
> +    return jsonify({"success": True})
With `cors` gone, I believe `jsonify` becomes redundant: Flask will automatically convert `dict` to JSON.

2021-02-02 10:19 UTC, fuglede commented on api/api.py
> +dotenv.load_dotenv(Path(__file__).parent / '../app/.env.local')
Slight mix of concerns that this lives in `app` (as opposed to the root). Is that unavoidable?

2021-02-03 08:41 UTC, Japanuspus commented on api/api.py
> +dotenv.load_dotenv(Path(__file__).parent / '../app/.env.local')
Totally agree. This was just the lazy solution as I only had to configure one of the parts. Will check for a way to do this on the vue-side as well.

2021-02-03 09:16 UTC, Japanuspus commented on api/api.py
> +dotenv.load_dotenv(Path(__file__).parent / '../app/.env.local')
Couldn't find an obvious place to hook into the load process on the vue-side. Easiest way to move this to root would probably be to roll our own config system on the Vue-side. So wontfix for now...

2021-02-06 12:42 UTC, merged